name: angular
run-name: ${{ github.actor }} deploy angular app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g @angular/cli

      - name: Install
        run: npm install

      - name: Build Angular project
        run: ng build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_CONFIG_SERVER: ${{ secrets.SSH_CONFIG_SERVER }}
        run: |
          mkdir -p /home/runner/.ssh
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > /home/runner/.ssh/known_hosts
          echo "$SSH_CONFIG_SERVER" > /home/runner/.ssh/config
          chmod 600 /home/runner/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ming@120.46.37.39 'bash -s' < deploy_script.sh

          #!/bin/bash
